---
- name: Deploy Splitwise app
  hosts: all
  tasks:
    - name: Copy docker compose file to host
      copy:
        src: docker-compose.yml
        dest: docker-compose.yml

    - name: Stop already running docker compose
      shell: docker-compose down

    - name: Remove already existing image
      docker_image:
        name: patro30/frontend
        state: absent

    - name: Pull updated image
      docker_image:
        name: patro30/frontend

    - name: Run docker compose
      shell: docker-compose up -d
